data:
  transform:
    rotation_range: 0 # degree
    width_shift_range: 0
    height_shift_range: 0
    zoom_range: 0.0
    fill_mode: 'nearest' # constant, nearest, reflect, wrap
    cval: 0
    horizontal_flip: true
    vertical_flip: false
    rescale: 0 # 0: unscale
  flow:
    directory: '/Users/daigo.hiroka/Data/stanford-dogs/images/Images'
    target_size: [64, 64] # only accepted
    batch_size: 32

model:
  discriminator_architecture: 'dcgan'
  discriminator_config:
    df_dim: 32
    name: 'discriminator'
  generator_architecture: 'dcgan'
  generator_config:
    gf_dim: 32
    name: 'generator'
    
train:
  epochs: 1
  discriminator_optimizer:
    learning_rate: 0.0001
    beta_1: 0
    beta_2: 0.999
  generator_optimizer:
    learning_rate: 0.0001
    beta_1: 0
    beta_2: 0.999
  z_dim: 120
  loss: 'bce' # hinge
  record_step: 100
